Repository Easy-Ti-cket/easy-ticket, pull requests merged in 2024-08, with the labels that each got.

#35 Feat: step2 페이지 구현
  src/components/forms/pay/PayMethodForm.jsx
  src/components/seatChart/SeatChart.jsx
  src/components/seatChart/seatGrid/Seat.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatSection/section/Section.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
  src/pages/practiceMode/step2/step2.txt
  src/routes.jsx
  src/store/atom.js
Labels: ✨Feat

#37 Feat: 티켓 매수 선택 컴포넌트 구현
  src/components/SeatCount.jsx
  src/components/seatChart/seatGrid/SeatGrid.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatInfo/SeatInfoStyles.jsx
  src/store/atom.js
  src/util/convertPriceObjectToArray.js
  src/util/convertPriceToNumber.js
  src/util/getRandomSeat.js
Labels: ✨Feat

#38 Feat: 내 예매정보 폼 구현
  .gitignore
  src/components/button/Button.module.css
  src/components/myBookingInfo/MyBookinfInfo.jsx
Labels: ✨Feat

#42 Feat: 모드 선택 페이지 구현
  src/assests/images/main.png
  src/pages/main/Main.jsx
  src/pages/practiceMode/selectMode/selectMode.jsx
  src/routes.jsx
Labels: ✨Feat

#40 Feat: 도움말 모달 컴포넌트 제작
  src/App.jsx
  src/components/Modal.jsx
  src/components/button/Button.module.css
  src/pages/ProgressContents.jsx
Labels: ✨Feat

#43 Refactor: 메인 페이지 로고 추가 및 배치 수정
  src/assests/images/main.png
  src/pages/main/Main.jsx
Labels: 🔧Refactor

#47 Refactor : 타이머 제어 및 추가 사항
  src/components/forms/pay/DetailPayForm.jsx
  src/components/forms/ticket/TicketMethod.jsx
  src/components/timer/Timer.jsx
  src/pages/ProgressContents.jsx
  src/pages/main/Main.jsx
Labels: 🔧Refactor

#51 Feat: 에러 수정 및 검사로직 구현
  src/components/calender/SelectCalender.jsx
  src/components/calender/calenderStyles.js
  src/components/forms/CardForm.jsx
  src/components/forms/pay/DetailPayForm.jsx
  src/components/forms/pay/PayMethodForm.jsx
  src/components/forms/ticket/TicketBuyer.jsx
  src/components/forms/ticket/TicketMethod.jsx
  src/components/myBookingInfo/MyBookingInfo.jsx
  src/hooks/useForm.js
  src/pages/PrivateRoute.jsx
  src/pages/ProgressContents.jsx
  src/pages/practiceMode/step0/Intro.jsx
  src/pages/practiceMode/step1/SelectRound.jsx
  src/pages/practiceMode/step3/SeatPriceCheck.jsx
  src/pages/practiceMode/step4/CardPay.jsx
  src/pages/practiceMode/step4/SelectPayMethod.jsx
Labels: 🐛Fix, 🔧Refactor

#52 Refactor: 포스터 날짜 및 시간 포맷 변경
  src/components/calender/SelectCalender.jsx
  src/components/poster/Poster.jsx
  src/components/poster/PosterInfo.jsx
  src/components/poster/PosterList.jsx
  src/components/poster/poster.json
  src/pages/practiceMode/step1/SelectRound.jsx
  src/util/date.js
  src/util/time.js
Labels: 🐛Fix, 🔧Refactor

#49 Feat:themProvider 기본 적용 및 프로그래스바 임시 적용
  src/App.jsx
  src/components/ProgressBar.jsx
  src/components/header/nav/subNav/SubNav.jsx
  src/pages/Test.jsx
  src/pages/challengeMode/interpark/1.txt
  src/pages/challengeMode/melonticket/2.txt
  src/pages/challengeMode/ticketlink/3.txt
  src/pages/challengeMode/yes24/4.txt
  src/pages/practiceMode/selectMode/selectMode.jsx
  src/pages/practiceMode/selectSite/selectSite.jsx
  src/store/atom.js
  src/styles/ThemeProvider.jsx
  src/styles/theme.js
Labels: ✨Feat

#50 Feat: 안심예매 캡차인증 컴포넌트 구현
  src/assests/images/icons/refresh.svg
  src/assests/images/icons/voice.svg
  src/components/modal/Modal.jsx
  src/components/secureModal/SecureModal.jsx
  src/pages/ProgressContents.jsx
  src/util/captcha.js
  src/util/getRandomString.js
  src/util/speechVoice.js
Labels: ✨Feat, 🔧Refactor

#55 Fix: 프로그래스 바 및 페이지 themeSite 적용 수정
  src/App.jsx
  src/components/ProgressBar.jsx
  src/components/header/nav/Nav.jsx
  src/index.css
  src/pages/Layout.jsx
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/interpark/SelectRoundInterpark.jsx
  src/pages/main/Main.jsx
  src/pages/practiceMode/selectLevel/SelectLevel.jsx
  src/pages/practiceMode/selectMode/selectMode.jsx
  src/pages/practiceMode/selectSite/selectSite.jsx
  src/pages/practiceMode/step0/Intro.jsx
  src/routes.jsx
  src/store/atom.js
  src/styles/CustomThemeProvider.jsx
  src/styles/ThemeProvider.jsx
  src/styles/theme.js
  src/util/resetAtom.js
Labels: 🐛Fix, 🔧Refactor

#57 Refactor: theme 적용 전 UI 수정
  src/components/Animation.jsx
  src/components/ProgressBar.jsx
  src/components/SeatCount.jsx
  src/components/button/Button.module.css
  src/components/calender/calenderStyles.js
  src/components/forms/ticket/TicketBuyer.jsx
  src/components/forms/ticket/TicketMethod.jsx
  src/components/header/Header.jsx
  src/components/header/nav/Nav.jsx
  src/components/header/nav/subNav/SubNav.jsx
  src/components/myBookingInfo/MyBookingInfo.jsx
  src/components/poster/PosterList.jsx
  src/components/seatChart/SeatChart.jsx
  src/components/seatChart/seatGrid/Seat.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatInfo/SeatInfoStyles.jsx
  src/components/seatSection/SeatSection.jsx
  src/components/seatSection/section/Section.jsx
  src/index.css
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/step0/ChallangeIntro.jsx
  src/pages/challengeMode/step0/introMessage/ChallangeIntroMessage.jsx
  src/pages/challengeMode/step0/introMessage/introText/IntroText.css
  src/pages/challengeMode/step0/introMessage/introText/IntroText.jsx
  src/pages/practiceMode/selectSite/selectSite.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
  src/pages/practiceMode/step5/Step5.jsx
  src/routes.jsx
  src/styles/theme.js
Labels: 🐛Fix, ✨Feat, 🔧Refactor

#56 Feat: esc 누를 경우 모달 생성 제어
  src/assests/images/icons/playPause/pause.svg
  src/assests/images/icons/playPause/play.svg
  src/assests/images/icons/playPause/stop.svg
  src/assests/images/icons/site/interpark.svg
  src/assests/images/icons/site/melonticket.svg
  src/assests/images/icons/site/tickelink.svg
  src/assests/images/icons/site/yes24.svg
  src/assests/logo.png
  src/components/button/Button.module.css
  src/components/modal/EscModalContents.jsx
  src/components/modal/Modal.jsx
  src/components/timer/Timer.jsx
  src/pages/ProgressContents.jsx
  src/pages/Test.jsx
  src/pages/practiceMode/selectMode/SelectMode.jsx
  src/pages/practiceMode/selectSite/SelectSite.jsx
  src/routes.jsx
Labels: ✨Feat

#58 Fix: themeSite 새로고침 오류 해결
  src/components/ProgressBar.jsx
  src/pages/PrivateRoute.jsx
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/selectSite/SelectSite.jsx
  src/pages/challengeMode/step0/ChallangeIntro.jsx
  src/pages/challengeMode/step0/introMessage/introText/IntroText.jsx
  src/pages/challengeMode/yes24/4.txt
  src/pages/challengeMode/yes24/SelectPerformYes24.jsx
  src/pages/main/Main.jsx
  src/pages/selectMode/SelectMode.jsx
  src/routes.jsx
  src/store/atom.js
  src/styles/CustomThemeProvider.jsx
Labels: 🐛Fix

#63 Fix: resetAtom 동작 안되는 오류 해결 / timer 제어 리팩토링 / 헤더 Design 수정 및 로고 클릭 시 메인화면 이동 기능 구현
  src/components/ProgressBar.jsx
  src/components/button/Button.module.css
  src/components/header/Header.jsx
  src/components/header/nav/Nav.jsx
  src/components/header/nav/subNav/SubNav.jsx
  src/components/modal/EscModalContents.jsx
  src/components/modal/GoToMainModalCont.jsx
  src/components/modal/Modal.jsx
  src/components/myBookingInfo/MyBookingInfo.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/timer/Timer.jsx
  src/pages/Layout.jsx
  src/pages/PrivateRoute.jsx
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/components/1.txt
  src/pages/challengeMode/interpark/step1/PosterInterpark.jsx
  src/pages/challengeMode/interpark/step1/SelectRoundInterpark.jsx
  src/pages/challengeMode/interpark/step2/SelectSeatInterpark.jsx
  src/pages/challengeMode/interpark/step3/SelectPriceInterpark.jsx
  src/pages/challengeMode/intro/ChallangeIntro.jsx
  src/pages/challengeMode/intro/introMessage/ChallangeIntroMessage.jsx
  src/pages/challengeMode/intro/introMessage/introText/IntroText.css
  src/pages/challengeMode/intro/introMessage/introText/IntroText.jsx
  src/pages/challengeMode/selectSite/SelectSite.jsx
  src/pages/challengeMode/yes24/SelectPerformYes24.jsx
  src/pages/main/Main.jsx
  src/pages/practiceMode/selectLevel/SelectLevel.jsx
  src/pages/practiceMode/step0/introMessage/IntroMessage.jsx
  src/pages/practiceMode/step4/CardPay.jsx
  src/pages/practiceMode/step4/SelectPayMethod.jsx
  src/pages/practiceMode/step5/Step5.jsx
  src/pages/selectMode/SelectMode.jsx
  src/routes.jsx
  src/store/atom.js
  src/styles/CustomThemeProvider.jsx
  src/util/resetAtom.js
  src/util/resetThemeSite.js
Labels: 🔧Refactor, 🎨Design

#64 Feat: Text 렌더링 구현
  src/hooks/text/TextBox.jsx
  src/hooks/text/TextHelpBox.jsx
  src/hooks/text/help/help0/help0Text.jsx
  src/hooks/text/help/help1/help1Text.jsx
  src/hooks/text/help/help2/help2Text.jsx
  src/hooks/text/help/help3/help3Text.jsx
  src/hooks/text/help/help4/help4Text.jsx
  src/hooks/text/step/step1/useStep1Text.jsx
  src/hooks/text/step/step2/useStep2Text.jsx
  src/hooks/text/step/step3/step3Text.jsx
  src/hooks/text/step/step4/step4Text.jsx
  src/hooks/useText.js
  src/pages/Layout.jsx
  src/pages/ProgressContents.jsx
  src/pages/Test.jsx
  src/pages/practiceMode/selectLevel/SelectLevel.jsx
  src/pages/practiceMode/step0/Intro.jsx
  src/pages/practiceMode/step0/introMessage/IntroMessage.jsx
  src/pages/practiceMode/step1/SelectPerformance.jsx
  src/pages/practiceMode/step1/SelectRound.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
  src/pages/practiceMode/step3/SeatPriceCheck.jsx
  src/pages/practiceMode/step4/CardPay.jsx
  src/pages/practiceMode/step4/SelectPayMethod.jsx
  src/routes.jsx
  src/store/atom.js
  src/styles/CustomThemeProvider.jsx
  src/util/resetAtom.js
Labels: ✨Feat, 🎨Design
