Repository Easy-Ti-cket/easy-ticket, pull requests merged in 2024-09, with the labels that each got.

#74 Refactor: 실전모드 각사이트 프로그래스바 리팩토링
  src/components/ProgressBar.jsx
  src/components/header/nav/subNav/SubNav.jsx
  src/components/progressBar/ProgressBar.jsx
  src/components/progressBar/progressStyle/DefaultProgressStyle.jsx
  src/components/progressBar/progressStyle/InterParkProgressBarStyle.jsx
  src/components/progressBar/progressStyle/MelonProgressStyle.jsx
  src/components/progressBar/progressStyle/TicketLinkProgressStyle.jsx
  src/components/progressBar/progressStyle/Yes24ProgressStyle.jsx
  src/hooks/useProgressStyle.js
  src/index.css
  src/pages/ProgressContents.jsx
  src/store/atom.js
Labels: 🔧Refactor, 🎨Design

#78 Refactor: 캘린더 컴포넌트에 에러 툴팁 추가
  src/components/calendar/SelectCalendar.jsx
  src/components/calendar/calendarStyles.js
  src/pages/challengeMode/interpark/step1/SelectRoundInterpark.jsx
  src/pages/challengeMode/melonticket/step1/SelectRoundMelonticket.jsx
  src/pages/challengeMode/ticketlink/step1/SelectRoundTicketlink.jsx
  src/pages/challengeMode/yes24/step1/SelectRoundYes24.jsx
  src/pages/practiceMode/step1/SelectRound.jsx
Labels: 🔧Refactor, 🎨Design

#76 Feat: Record 페이지 구현
  package-lock.json
  package.json
  src/apis/loadUserData.js
  src/apis/saveUserData.js
  src/components/button/Button.jsx
  src/components/button/Button.module.css
  src/components/header/Header.jsx
  src/pages/challengeMode/components/record/RecordNavigate.jsx
  src/pages/challengeMode/melonticket/step3/SelectPriceMelon.jsx
  src/pages/challengeMode/outro/Record.jsx
  src/pages/challengeMode/record/Record.jsx
  src/pages/challengeMode/record/RecordStyle.js
  src/pages/practiceMode/step4/SelectPayMethod.jsx
  src/routes.jsx
  src/util/Paging.jsx
Labels: ✨Feat, 🔧Refactor, 🎨Design

#79 Feat: 실전모드 melon티켓 구현
  src/components/forms/FormStyle.js
  src/components/forms/pay/PayMethodForm.jsx
  src/pages/challengeMode/components/AgreementMelon.jsx
  src/pages/challengeMode/components/OrdererInfoMelon.jsx
  src/pages/challengeMode/components/PosterSection.jsx
  src/pages/challengeMode/components/TiketMethod/TicketMethodMelon.jsx
  src/pages/challengeMode/components/payMethod/DetailPayFormMelon.jsx
  src/pages/challengeMode/components/selectDiscount/SelectDiscountMelon.jsx
  src/pages/challengeMode/melonticket/step1/SelectRoundMelonticket.jsx
  src/pages/challengeMode/melonticket/step2/SelectSeatMelon.jsx
  src/pages/challengeMode/melonticket/step2/SelectSeatMelonticket.jsx
  src/pages/challengeMode/melonticket/step3/SelectPriceMelon.jsx
  src/pages/challengeMode/melonticket/step4/SelectPayMethodMelon.jsx
  src/routes.jsx
Labels: ✨Feat

#83 Fix: record 종속성 배열 및 렌더링 순서 문제 해결
  src/pages/challengeMode/record/Record.jsx
Labels: 🐛Fix

#81 Refact: 알맞은 좌석 클릭시 검은색 테두리 생성/ Fix: 단계별 텍스트 잘못 렌더링 되던거 수정, CardPay 새로고침 시 progressAtom 초기화 문제 고침, resetAtom()에서 fakeAllowedSeat 도 초기화하도록 수정
  src/components/seatChart/seatGrid/Seat.jsx
  src/hooks/text/step/step2/useStep2Text.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
  src/pages/practiceMode/step4/CardPay.jsx
  src/util/resetAtom.js
Labels: 🐛Fix, 🔧Refactor

#85 Fix: 실전모드 step0 화면 타이머 리셋 오류 수정
  src/components/forms/pay/PayMethodForm.jsx
  src/components/forms/ticket/TicketBuyer.jsx
  src/components/forms/ticket/TicketMethod.jsx
  src/components/forms/ticket/TicketMethodStyle.js
  src/components/myBookingInfo/MyBookingInfo.jsx
  src/components/myBookingInfo/MyBookingInfoContainer.js
  src/components/poster/Poster.jsx
  src/components/poster/poster.json
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatSection/SeatSection0.jsx
  src/components/seatSection/SeatSection1.jsx
  src/components/seatSection/SeatSection2.jsx
  src/components/seatSection/SeatSection3.jsx
  src/components/timer/Timer.jsx
  src/components/tooltip/ErrorTooltip.jsx
  src/hooks/useBookingValidate.js
  src/hooks/usePaymentValidate.js
  src/pages/Layout.jsx
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/components/AgreementMelon.jsx
  src/pages/challengeMode/components/TiketMethod/TicketMethodMelon.jsx
  src/pages/challengeMode/components/TiketMethod/TicketMethodTicketlink.jsx
  src/pages/challengeMode/components/payMethod/SelectPayMethodChallenge.jsx
  src/pages/challengeMode/components/payMethod/payMethodStyle.js
  src/pages/challengeMode/components/seatCount/SeatCountTicketlink.jsx
  src/pages/challengeMode/components/selectPrice/BookingPersonCheckBox.jsx
  src/pages/challengeMode/components/selectPrice/SelectPriceCheckBox.jsx
  src/pages/challengeMode/interpark/step3-step4/SelectPriceInterpark.jsx
  src/pages/challengeMode/interpark/step5-1/SelectPayMethodInterPark.jsx
  src/pages/challengeMode/melonticket/step3/SelectPriceMelon.jsx
  src/pages/challengeMode/melonticket/step4/SelectPayMethodMelon.jsx
  src/pages/challengeMode/ticketlink/step3-step4/MyBookingInfo.jsx
  src/pages/challengeMode/ticketlink/step3-step4/SelectPriceTicketlink.jsx
  src/pages/challengeMode/ticketlink/step3-step4/ticket/TicketBuyer.jsx
  src/pages/challengeMode/ticketlink/step3-step4/ticket/TicketMethod.jsx
  src/pages/challengeMode/ticketlink/step5/SelectPayMethodTicketlink.jsx
  src/pages/practiceMode/step1/SelectPerformance.jsx
  src/pages/practiceMode/step3/SeatPriceCheck.jsx
  src/pages/selectMode/SelectMode.jsx
  src/store/atom.js
  src/util/getRandomSeat.js
Labels: 🐛Fix

#84 Feat/Fix: 모든 실전모드 사이트 검사 로직 추가 / 티켓링크 step4 코드 리팩토링 (논의 필수!!!!)
  src/pages/challengeMode/components/selectPrice/BookingPersonCheckBox.jsx
  src/pages/challengeMode/components/ticketMethod/TicketMethodMelon.jsx
  src/pages/challengeMode/components/ticketMethod/TicketMethodTicketlink.jsx
  src/pages/challengeMode/ticketlink/step3-step4/SelectPriceTicketlink.jsx
Labels: 🐛Fix, ✨Feat, 🔧Refactor

#87 Fix: 새로고침시 텍스트 렌더링 잘못 되던거 고침, step2 새로고침시 상태 초기화
  src/pages/challengeMode/components/ticketMethod/TicketMethodMelon.jsx
  src/pages/challengeMode/interpark/step2/SelectSeatInterpark.jsx
  src/pages/practiceMode/step1/SelectPerformance.jsx
  src/pages/practiceMode/step1/SelectRound.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
Labels: 🐛Fix

#88 Feat: 파이어베이스 배포 테스트 및 Github Action workflows 설정
  .firebaserc
  .github/workflows/develop.yml
  .gitignore
  firebase.json
  package-lock.json
  package.json
  src/components/modal/TimeoutModal.jsx
  src/pages/ProgressContents.jsx
  src/util/resetAtom.js
Labels: ✨Feat, 📦️Chore

#89 Refactor: Modal 관련 폴더명 및 파일명 수정 및 SelectSeatChallengeMode로 통일
  src/components/header/Header.jsx
  src/components/header/nav/Nav.jsx
  src/components/header/nav/subNav/SubNav.jsx
  src/components/modal/modalContents/EscModalContents.jsx
  src/components/modal/modalContents/GoToMainModalContents.jsx
  src/components/modal/modalContents/SecureModalContents.jsx
  src/components/modal/modalContents/TimeoutModalContents.jsx
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/interpark/step2/SelectSeatInterpark.jsx
  src/pages/challengeMode/melonticket/step2/SelectSeatMelon.jsx
  src/pages/challengeMode/selectPerformance/SelectPerformanceChallengeMode.jsx
  src/pages/challengeMode/selectSeat/SelectSeatChallangeMode.jsx
  src/pages/challengeMode/ticketlink/step2/SelectSeatTicketlink.jsx
  src/pages/challengeMode/yes24/step2/SelectSeatYes24.jsx
  src/routes.jsx
Labels: 🔧Refactor

#92 Feat: 연습모드 완료시(step5 도달시) 연습횟수 증가
  src/pages/ProgressContents.jsx
  src/pages/practiceMode/step5/Step5.jsx
  src/pages/selectMode/SelectMode.jsx
  src/store/atom.js
  src/util/resetAtom.js
Labels: ✨Feat

#95 Fix: 좌석 컴포넌트의 배치 및 atom 초기화 버그 수정
  src/components/SeatCount.jsx
  src/components/card/settings/vertical/VerticalFront.jsx
  src/components/seatChart/SeatChart1.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/hooks/useBookingValidate.js
  src/pages/ProgressContents.jsx
  src/pages/challengeMode/selectSeat/SelectSeatChallangeMode.jsx
Labels: 🐛Fix

#96 Fix: 타임아웃 모달창에 로딩을 추가해 새로고침해도 렌더링되지 않도록 수정
  src/pages/ProgressContents.jsx
Labels: 🐛Fix

#97 Feat: 실전모드+연습모드 alert -> 안내문구로 수정
  public/assets/images/icons/errorInfo.svg
  src/components/Paging.jsx
  src/components/SeatCount.jsx
  src/components/button/Button.module.css
  src/components/errorText/ErrorText.jsx
  src/components/forms/CardForm.jsx
  src/components/forms/pay/DetailPayForm.jsx
  src/components/forms/pay/PayMethodForm.jsx
  src/components/forms/ticket/TicketBuyer.jsx
  src/components/forms/ticket/TicketMethod.jsx
  src/components/forms/ticket/TicketMethodStyle.js
  src/components/modal/modalContents/SecureModalContents.jsx
  src/components/poster/PosterList.jsx
  src/components/seatChart/SeatChart.jsx
  src/components/seatChart/SeatChart1.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatSection/SeatSection.jsx
  src/hooks/useBookingValidate.js
  src/hooks/usePaymentValidate.js
  src/pages/challengeMode/components/AgreementMelon.jsx
  src/pages/challengeMode/components/payMethod/DetailPayFormMelon.jsx
  src/pages/challengeMode/components/payMethod/PayMethodCheckBox.jsx
  src/pages/challengeMode/components/payMethod/SelectPayMethodChallenge.jsx
  src/pages/challengeMode/components/seatCount/SeatCountTicketlink.jsx
  src/pages/challengeMode/components/ticketMethod/TicketMethodTicketlink.jsx
  src/pages/challengeMode/interpark/step1/SelectRoundInterpark.jsx
  src/pages/challengeMode/interpark/step3-step4/SelectPriceInterpark.jsx
  src/pages/challengeMode/interpark/step5-1/SelectPayMethodInterPark.jsx
  src/pages/challengeMode/melonticket/step1/SelectRoundMelonticket.jsx
  src/pages/challengeMode/melonticket/step3/SelectPriceMelon.jsx
  src/pages/challengeMode/melonticket/step4/SelectPayMethodMelon.jsx
  src/pages/challengeMode/outro/Outro.jsx
  src/pages/challengeMode/record/Record.jsx
  src/pages/challengeMode/selectSeat/SelectSeatChallangeMode.jsx
  src/pages/challengeMode/ticketlink/step1/SelectRoundTicketlink.jsx
  src/pages/challengeMode/ticketlink/step3-step4/SelectPriceTicketlink.jsx
  src/pages/challengeMode/yes24/step1/SelectRoundYes24.jsx
  src/pages/challengeMode/yes24/step5/SelectPayMethodYes24.jsx
  src/pages/practiceMode/step1/SelectPerformance.jsx
  src/pages/practiceMode/step1/SelectRound.jsx
  src/pages/practiceMode/step2/SelectSeat.jsx
  src/pages/practiceMode/step3/SeatPriceCheck.jsx
  src/pages/practiceMode/step4/CardPay.jsx
Labels: 🐛Fix, ✨Feat, 🔧Refactor

#99 Refactor: 멜론티켓 step5-1 페이지 예매자 동의 로직 수정
  src/components/header/nav/Nav.jsx
  src/pages/challengeMode/components/AgreementMelon.jsx
Labels: 🔧Refactor

#98 Update README.md
  README.md
Labels: 📑Docs

#102 Feat: favicon 및 웹사이트명 설정
  index.html
  public/favicon.ico
Labels: ✨Feat

#103 Fix: 실전모드 progressStep 설정
  src/pages/challengeMode/interpark/step3-step4/SelectPriceInterpark.jsx
  src/pages/challengeMode/interpark/step5-1/SelectPayMethodInterPark.jsx
  src/pages/challengeMode/ticketlink/step3-step4/SelectPriceTicketlink.jsx
  src/pages/challengeMode/ticketlink/step5/SelectPayMethodTicketlink.jsx
  src/pages/challengeMode/yes24/step5/SelectPayMethodYes24.jsx
  src/pages/practiceMode/step4/CardPay.jsx
Labels: 🐛Fix

#105 Refactor: subnav 사이트 순서 통일
  src/components/header/nav/subNav/SubNav.jsx
Labels: 🔧Refactor

#106 Docs: 리드미 기능 소개 사진 추가 및 일부 문구 단순화
  README.md
  public/readme/challenge_mode.png
  public/readme/main_page.png
  public/readme/practice_mode.png
  public/readme/view_rank.png
Labels: 📑Docs

#104 Fix : 서버에서 몇 사이트 기록이 focus되지 않는 문제
  src/pages/challengeMode/record/Record.jsx
Labels: 🐛Fix
