Repository Easy-Ti-cket/easy-ticket, pull requests merged in 2024-07, with the labels that each got.

#2 Feature/components progressbar
  src/components/1.txt
  src/components/ProgressBar.jsx
Labels: 🐛Fix, ✨Feat, 🎨Design

#4 Chore: ESLint와 Prettier 설정 및 husky 테스트
  .eslintcache
  .gitattributes
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: 📦️Chore

#7 Feat: layout , ProgressContents 구현
  src/App.jsx
  src/components/header/Header.jsx
  src/pages/2.txt
  src/pages/Layout.jsx
  src/pages/ProgressContents.jsx
Labels: ✨Feat, 🎨Design

#5 Feat: Timer 컴포넌트 구현
  src/assests/images/icons/timer.svg
  src/components/Timer/Timer.jsx
Labels: ✨Feat

#9 Feature/components calender
  package-lock.json
  package.json
  src/components/calender/SelectCalender.jsx
  src/components/calender/calenderStyles.js
Labels: ✨Feat, 🎨Design

#8 Feat : input 컴포넌트 (radio, text) 구현
  src/components/Animation.jsx
  src/components/input/Input.jsx
  src/components/input/InputRadio.jsx
  src/components/input/InputText.jsx
Labels: ✨Feat, 🔧Refactor, 🎨Design

#10 Refactor: Jotai 상태관리 라이브러리 사용하여 타이머 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/App.jsx
  src/components/Timer/Timer.jsx
  src/store/atom.js
Labels: 🔧Refactor

#13 Refactor: progressAtom을 사용해 단계수정
  src/components/ProgressBar.jsx
Labels: 🔧Refactor

#24 Design: 헤더 폰트사이즈 및 너비 수정
  src/components/header/Header.jsx
  src/components/header/nav/Nav.jsx
  src/components/header/nav/subNav/SubNav.jsx
Labels: 🎨Design

#15 Feat: SeatChart component 구현
  src/App.jsx
  src/components/seatChart/SeatChart.jsx
  src/components/seatChart/seatGrid/Seat.jsx
  src/components/seatChart/seatGrid/SeatGrid.jsx
  src/store/atom.js
  src/util/getRandomInt.js
Labels: ✨Feat

#16 Feat: SeatInfo 컴포넌트 구현
  src/App.jsx
  src/components/SeatInfo.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatInfo/SeatInfoStyles.jsx
  src/store/atom.js
Labels: ✨Feat

#19 Feat : 카드번호 및 cvc 랜덤 생성 컴포넌트 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assests/images/cards/CardABack.svg
  src/assests/images/cards/CardAFront.svg
  src/assests/images/cards/CardBBack.svg
  src/assests/images/cards/CardBFront.svg
  src/assests/images/cards/card2_back.svg
  src/assests/images/cards/card2_front.svg
  src/assests/images/cards/card3_back.svg
  src/assests/images/cards/card3_front.svg
  src/components/card/Card.jsx
  src/components/card/settings/CardStyles.js
  src/components/card/settings/horizontal/HorizonBack.jsx
  src/components/card/settings/horizontal/HorizonFront.jsx
  src/components/card/settings/vertical/VerticalBack.jsx
  src/components/card/settings/vertical/VerticalFront.jsx
  src/hooks/useRandomNum.js
  src/store/atom.js
  vite.config.js
Labels: ✨Feat

#29 Feat: Step0 - Intro 페이지 구현
  src/pages/step0/Intro.jsx
  src/pages/step0/introMessage/IntroMessage.jsx
  src/pages/step0/introMessage/introText/IntroText.css
  src/pages/step0/introMessage/introText/IntroText.jsx
  src/pages/step0/step0.txt
  src/routes.jsx
Labels: ✨Feat

#31 Fix: allowedSeatAtom 삭제 문제 해결
  src/store/atom.js
Labels: 🐛Fix

#21 Feat: SeatSection 구현
  src/App.jsx
  src/components/SeatInfo.jsx
  src/components/seatInfo/SeatInfo.jsx
  src/components/seatInfo/SeatInfoStyles.jsx
  src/components/seatSection/SeatSection.jsx
  src/components/seatSection/section/Section.jsx
  src/store/atom.js
Labels: ✨Feat, 🔧Refactor

#28 Feat: main page 구현
  src/pages/main/Main.jsx
  src/routes.jsx
  src/store/atom.js
Labels: ✨Feat

#32 Feat: 난이도 선택 화면 구현
  src/pages/selectLevel/SelectLevel.jsx
  src/routes.jsx
  src/store/atom.js
Labels: ✨Feat

#34 Feat: step4 UI 구현 및 기능 구현
  src/components/card/Card.jsx
  src/components/forms/CardForm.jsx
  src/components/forms/pay/DetailPayForm.jsx
  src/components/forms/pay/PayMethodForm.jsx
  src/components/input/Input.jsx
  src/components/input/InputText.jsx
  src/hooks/useForm.js
  src/hooks/useRandomNum.js
  src/pages/step4/CardPay.jsx
  src/pages/step4/SelectPayMethod.jsx
  src/pages/step4/step4.txt
  src/routes.jsx
Labels: ✨Feat, 🔧Refactor
